version: '3'
services:
  app:
    container_name: gin-demo
    build: .
    ports: 
      - 80:80
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - gin-demo-mysql
    networks:
      - gin-demo-stack

  gin-demo-mysql:
    image: mysql:5.7
    container_name: gin-demo_db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - gin-demo-stack
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - gin-demo-mysql
    environment:
      - PMA_HOST=gin-demo-mysql
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - gin-demo-stack


volumes:
  api:
  database_mysql:

networks:
  gin-demo-stack:
    driver: bridge

