version: "3.3"
services:
  gin-demo:
    container_name: gin-demo-deploy
    build: .
    ports:
      - 9369:80
    depends_on:
      - mysql
    volumes:
      - ../:/app
      - ./.env:/app/.env
    #restart: on-failure
  mysql:
    container_name: gin-demo-mysql
    restart: on-failure
    image: mysql:8
    env_file:
      - ./.env
    ports:
      - 3366:3306
